# Server
server.port=8080

# Application
spring.application.name=salud360-integracion

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# Apache Camel
camel.springboot.name=Salud360CamelApp
camel.springboot.main-run-controller=true

# RabbitMQ Camel settings
camel.component.rabbitmq.hostname=localhost
camel.component.rabbitmq.port-number=5672
camel.component.rabbitmq.username=admin
camel.component.rabbitmq.password=admin123
camel.component.rabbitmq.auto-ack=true

# File paths
app.outbox.path=data/outbox
app.errors.path=data/errors
app.csv.filename=auditoria-citas.csv
app.errors.filename=citas-rechazadas.log

# Logging
logging.level.edu.udla.integracion=DEBUG
logging.level.org.apache.camel=INFO
